
<?php 
// complete liste of words ()
$words = array(
    // verbs
    array("type" => "verb", "content" => "est", "plural" => "sont")
    , array("type" => "verb", "content" => "paraît", "plural" => "paraissent")
    , array("type" => "verb", "content" => "demeure")
    , array("type" => "verb", "content" => "devient", "plural" => "deviennent")
    , array("type" => "verb", "content" => "reste")
    , array("type" => "verb", "content" => "a l'air" , "plural" => "ont l'air")
    , array("type" => "verb", "content" => "passe pour" , "plural" => "passent pour")
    , array("type" => "verb", "content" => "naît" , "plural" => "naissent")
    , array("type" => "verb", "content" => "meurt" , "plural" => "meurent")

    // nouns
    , array("type" => "noun", "content" => "instant") 
    , array("type" => "noun", "content" => "intérêt") 
    , array("type" => "noun", "content" => "intérieur") 
    , array("type" => "noun", "content" => "jardin") 
    , array("type" => "noun", "content" => "jour") 
    , array("type" => "noun", "content" => "journal", "plural" => "journaux") 
    , array("type" => "noun", "content" => "lieu", "plural" => "lieux") 
    , array("type" => "noun", "content" => "maître") 
    , array("type" => "noun", "content" => "mari") 
    , array("type" => "noun", "content" => "mariage") 
    , array("type" => "noun", "content" => "matin") 
    , array("type" => "noun", "content" => "médecin") 
    , array("type" => "noun", "content" => "mètre") 
    , array("type" => "noun", "content" => "milieu", "plural" => "milieux") 
    , array("type" => "noun", "content" => "million") 
    , array("type" => "noun", "content" => "moment") 
    , array("type" => "noun", "content" => "monde") 
    , array("type" => "noun", "content" => "monsieur") 
    , array("type" => "noun", "content" => "mouvement") 
    , array("type" => "noun", "content" => "moyen") 
    , array("type" => "noun", "content" => "noir") 
    , array("type" => "noun", "content" => "nouveau", "plural" => "nouveaux") 
    , array("type" => "noun", "content" => "numéro") 
    , array("type" => "noun", "content" => "oeil", "plural" => "yeux") 
    , array("type" => "noun", "content" => "oiseau", "plural" => "oiseaux") 
    , array("type" => "noun", "content" => "oncle") 
    , array("type" => "noun", "content" => "ordre") 
    , array("type" => "noun", "content" => "papa") 
    , array("type" => "noun", "content" => "papier") 
    , array("type" => "noun", "content" => "parent") 
    , array("type" => "noun", "content" => "passage") 
    , array("type" => "noun", "content" => "passé") 
    , array("type" => "noun", "content" => "patron") 
    , array("type" => "noun", "content" => "père") 
    , array("type" => "noun", "content" => "petit") 
    , array("type" => "noun", "content" => "peuple") 
    , array("type" => "noun", "content" => "pied") 
    , array("type" => "noun", "content" => "plaisir") 
    , array("type" => "noun", "content" => "plan") 
    , array("type" => "noun", "content" => "point") 
    , array("type" => "noun", "content" => "pouvoir") 
    , array("type" => "noun", "content" => "premier") 
    , array("type" => "noun", "content" => "présent") 
    , array("type" => "noun", "content" => "président") 
    , array("type" => "noun", "content" => "prince") 
    , array("type" => "noun", "content" => "problème") 
    , array("type" => "noun", "content" => "quartier") 
    , array("type" => "noun", "content" => "rapport") 
    , array("type" => "noun", "content" => "regard") 
    , array("type" => "noun", "content" => "reste") 
    , array("type" => "noun", "content" => "retard") 
    , array("type" => "noun", "content" => "retour") 
    , array("type" => "noun", "content" => "rêve") 
    , array("type" => "noun", "content" => "salut") 
    , array("type" => "noun", "content" => "sang") 
    , array("type" => "noun", "content" => "secret") 
    , array("type" => "noun", "content" => "seigneur") 
    , array("type" => "noun", "content" => "sentiment") 
    , array("type" => "noun", "content" => "service") 
    , array("type" => "noun", "content" => "seul") 
    , array("type" => "noun", "content" => "siècle") 
    , array("type" => "noun", "content" => "signe") 
    , array("type" => "noun", "content" => "silence") 
    , array("type" => "noun", "content" => "soir") 
    , array("type" => "noun", "content" => "soldat") 
    , array("type" => "noun", "content" => "soleil") 
    , array("type" => "noun", "content" => "sourire") 
    , array("type" => "noun", "content" => "souvenir") 
    , array("type" => "noun", "content" => "sujet") 
    , array("type" => "noun", "content" => "téléphone") 
    , array("type" => "noun", "content" => "train") 
    , array("type" => "noun", "content" => "travail", "plural" => "travaux") 
    , array("type" => "noun", "content" => "trou") 
    , array("type" => "noun", "content" => "truc") 
    , array("type" => "noun", "content" => "type") 
    , array("type" => "noun", "content" => "vent") 
    , array("type" => "noun", "content" => "ventre") 
    , array("type" => "noun", "content" => "verre") 
    , array("type" => "noun", "content" => "village") 
    , array("type" => "noun", "content" => "visage") 
    , array("type" => "noun", "content" => "voyage")
    , array("type" => "noun", "content" => "avis", "plural" => "avis") 
    , array("type" => "noun", "content" => "bois", "plural" => "bois") 
    , array("type" => "noun", "content" => "bras", "plural" => "bras") 
    , array("type" => "noun", "content" => "choix", "plural" => "choix") 
    , array("type" => "noun", "content" => "corps", "plural" => "corps") 
    , array("type" => "noun", "content" => "cours", "plural" => "cours") 
    , array("type" => "noun", "content" => "gars", "plural" => "gars") 
    , array("type" => "noun", "content" => "mois", "plural" => "mois") 
    , array("type" => "noun", "content" => "pays", "plural" => "pays") 
    , array("type" => "noun", "content" => "prix", "plural" => "prix") 
    , array("type" => "noun", "content" => "propos", "plural" => "propos") 
    , array("type" => "noun", "content" => "sens", "plural" => "sens") 
    , array("type" => "noun", "content" => "temps", "plural" => "temps") 
    , array("type" => "noun", "content" => "travers", "plural" => "travers") 
    , array("type" => "noun", "content" => "vieux", "plural" => "vieux") 
    , array("type" => "noun", "content" => "accord") 
    , array("type" => "noun", "content" => "agent") 
    , array("type" => "noun", "content" => "amour") 
    , array("type" => "noun", "content" => "appel") 
    , array("type" => "noun", "content" => "arbre") 
    , array("type" => "noun", "content" => "argent") 
    , array("type" => "noun", "content" => "avenir") 
    , array("type" => "noun", "content" => "avion") 
    , array("type" => "noun", "content" => "bateau", "plural" => "bateaux") 
    , array("type" => "noun", "content" => "bébé") 
    , array("type" => "noun", "content" => "besoin") 
    , array("type" => "noun", "content" => "bonheur") 
    , array("type" => "noun", "content" => "bonjour") 
    , array("type" => "noun", "content" => "bord") 
    , array("type" => "noun", "content" => "boulot") 
    , array("type" => "noun", "content" => "bout") 
    , array("type" => "noun", "content" => "bruit") 
    , array("type" => "noun", "content" => "bureau", "plural" => "bureaux") 
    , array("type" => "noun", "content" => "café") 
    , array("type" => "noun", "content" => "camp") 
    , array("type" => "noun", "content" => "capitaine") 
    , array("type" => "noun", "content" => "chat") 
    , array("type" => "noun", "content" => "chemin") 
    , array("type" => "noun", "content" => "chéri") 
    , array("type" => "noun", "content" => "cheval", "plural" => "chevaux") 
    , array("type" => "noun", "content" => "cheveu", "plural" => "cheveux") 
    , array("type" => "noun", "content" => "chien") 
    , array("type" => "noun", "content" => "ciel") 
    , array("type" => "noun", "content" => "client") 
    , array("type" => "noun", "content" => "cœur") 
    , array("type" => "noun", "content" => "coin") 
    , array("type" => "noun", "content" => "colonel") 
    , array("type" => "noun", "content" => "compte") 
    , array("type" => "noun", "content" => "copain") 
    , array("type" => "noun", "content" => "côté") 
    , array("type" => "noun", "content" => "coup") 
    , array("type" => "noun", "content" => "courant") 
    , array("type" => "noun", "content" => "début") 
    , array("type" => "noun", "content" => "départ") 
    , array("type" => "noun", "content" => "dieu", "plural" => "dieux") 
    , array("type" => "noun", "content" => "docteur") 
    , array("type" => "noun", "content" => "doigt") 
    , array("type" => "noun", "content" => "dollar") 
    , array("type" => "noun", "content" => "doute") 
    , array("type" => "noun", "content" => "droit") 
    , array("type" => "noun", "content" => "effet") 
    , array("type" => "noun", "content" => "endroit") 
    , array("type" => "noun", "content" => "ennemi") 
    , array("type" => "noun", "content" => "escalier") 
    , array("type" => "noun", "content" => "esprit") 
    , array("type" => "noun", "content" => "état") 
    , array("type" => "noun", "content" => "être") 
    , array("type" => "noun", "content" => "exemple") 
    , array("type" => "noun", "content" => "fait") 
    , array("type" => "noun", "content" => "film") 
    , array("type" => "noun", "content" => "fils", "plural" => "fils") 
    , array("type" => "noun", "content" => "flic") 
    , array("type" => "noun", "content" => "fond") 
    , array("type" => "noun", "content" => "français", "plural" => "français") 
    , array("type" => "noun", "content" => "frère") 
    , array("type" => "noun", "content" => "front") 
    , array("type" => "noun", "content" => "garçon") 
    , array("type" => "noun", "content" => "général", "plural" => "généraux") 
    , array("type" => "noun", "content" => "genre") 
    , array("type" => "noun", "content" => "goût") 
    , array("type" => "noun", "content" => "gouvernement") 
    , array("type" => "noun", "content" => "grand") 
    , array("type" => "noun", "content" => "groupe") 
    , array("type" => "noun", "content" => "haut") 
    , array("type" => "noun", "content" => "aide") 
    , array("type" => "noun", "content" => "gens", "plural" => "gens") 
    , array("type" => "noun", "content" => "chef") 
    , array("type" => "noun", "content" => "enfant") 
    , array("type" => "noun", "content" => "garde") 
    , array("type" => "noun", "content" => "geste") 
    , array("type" => "noun", "content" => "gosse") 
    , array("type" => "noun", "content" => "livre") 
    , array("type" => "noun", "content" => "merci") 
    , array("type" => "noun", "content" => "mort") 
    , array("type" => "noun", "content" => "professeur") 
    , array("type" => "noun", "content" => "tour") 
    , array("type" => "noun", "content" => "homme", "forcedElision" => true)
    , array("type" => "noun", "content" => "honneur", "forcedElision" => true)
    , array("type" => "noun", "content" => "hôtel", "forcedElision" => true)
    , array("type" => "noun", "content" => "ombre", "fem" => true)
    , array("type" => "noun", "content" => "part", "fem" => true)
    , array("type" => "noun", "content" => "poche", "fem" => true)
    , array("type" => "noun", "content" => "gauche", "fem" => true)
    , array("type" => "noun", "content" => "fois", "plural" => "fois", "fem" => true)
    , array("type" => "noun", "content" => "madame", "fem" => true)
    , array("type" => "noun", "content" => "paix", "plural" => "paix", "fem" => true)
    , array("type" => "noun", "content" => "voix", "plural" => "voix", "fem" => true)
    , array("type" => "noun", "content" => "affaire", "fem" => true)
    , array("type" => "noun", "content" => "année", "fem" => true)
    , array("type" => "noun", "content" => "arme", "fem" => true)
    , array("type" => "noun", "content" => "armée", "fem" => true)
    , array("type" => "noun", "content" => "attention", "fem" => true)
    , array("type" => "noun", "content" => "balle", "fem" => true)
    , array("type" => "noun", "content" => "boîte", "fem" => true)
    , array("type" => "noun", "content" => "bouche", "fem" => true)
    , array("type" => "noun", "content" => "carte", "fem" => true)
    , array("type" => "noun", "content" => "cause", "fem" => true)
    , array("type" => "noun", "content" => "chambre", "fem" => true)
    , array("type" => "noun", "content" => "chance", "fem" => true)
    , array("type" => "noun", "content" => "chose", "fem" => true)
    , array("type" => "noun", "content" => "classe", "fem" => true)
    , array("type" => "noun", "content" => "confiance", "fem" => true)
    , array("type" => "noun", "content" => "couleur", "fem" => true)
    , array("type" => "noun", "content" => "cour", "fem" => true)
    , array("type" => "noun", "content" => "cuisine", "fem" => true)
    , array("type" => "noun", "content" => "dame", "fem" => true)
    , array("type" => "noun", "content" => "dent", "fem" => true)
    , array("type" => "noun", "content" => "droite", "fem" => true)
    , array("type" => "noun", "content" => "école", "fem" => true)
    , array("type" => "noun", "content" => "église", "fem" => true)
    , array("type" => "noun", "content" => "envie", "fem" => true)
    , array("type" => "noun", "content" => "épaule", "fem" => true)
    , array("type" => "noun", "content" => "époque", "fem" => true)
    , array("type" => "noun", "content" => "équipe", "fem" => true)
    , array("type" => "noun", "content" => "erreur", "fem" => true)
    , array("type" => "noun", "content" => "espèce", "fem" => true)
    , array("type" => "noun", "content" => "face", "fem" => true)
    , array("type" => "noun", "content" => "façon", "fem" => true)
    , array("type" => "noun", "content" => "faim", "fem" => true)
    , array("type" => "noun", "content" => "famille", "fem" => true)
    , array("type" => "noun", "content" => "faute", "fem" => true)
    , array("type" => "noun", "content" => "femme", "fem" => true)
    , array("type" => "noun", "content" => "fenêtre", "fem" => true)
    , array("type" => "noun", "content" => "fête", "fem" => true)
    , array("type" => "noun", "content" => "fille", "fem" => true)
    , array("type" => "noun", "content" => "fleur", "fem" => true)
    , array("type" => "noun", "content" => "force", "fem" => true)
    , array("type" => "noun", "content" => "forme", "fem" => true)
    , array("type" => "noun", "content" => "guerre", "fem" => true)
    , array("type" => "noun", "content" => "gueule", "fem" => true)
    , array("type" => "noun", "content" => "idée", "fem" => true)
    , array("type" => "noun", "content" => "image", "fem" => true)
    , array("type" => "noun", "content" => "impression", "fem" => true)
    , array("type" => "noun", "content" => "jambe", "fem" => true)
    , array("type" => "noun", "content" => "joie", "fem" => true)
    , array("type" => "noun", "content" => "journée", "fem" => true)
    , array("type" => "noun", "content" => "langue", "fem" => true)
    , array("type" => "noun", "content" => "lettre", "fem" => true)
    , array("type" => "noun", "content" => "lèvre", "fem" => true)
    , array("type" => "noun", "content" => "ligne", "fem" => true)
    , array("type" => "noun", "content" => "lumière", "fem" => true)
    , array("type" => "noun", "content" => "main", "fem" => true)
    , array("type" => "noun", "content" => "maison", "fem" => true)
    , array("type" => "noun", "content" => "maman", "fem" => true)
    , array("type" => "noun", "content" => "manière", "fem" => true)
    , array("type" => "noun", "content" => "marche", "fem" => true)
    , array("type" => "noun", "content" => "merde", "fem" => true)
    , array("type" => "noun", "content" => "mer", "fem" => true)
    , array("type" => "noun", "content" => "mère", "fem" => true)
    , array("type" => "noun", "content" => "minute", "fem" => true)
    , array("type" => "noun", "content" => "musique", "fem" => true)
    , array("type" => "noun", "content" => "nuit", "fem" => true)
    , array("type" => "noun", "content" => "odeur", "fem" => true)
    , array("type" => "noun", "content" => "oreille", "fem" => true)
    , array("type" => "noun", "content" => "parole", "fem" => true)
    , array("type" => "noun", "content" => "partie", "fem" => true)
    , array("type" => "noun", "content" => "peau", "fem" => true)
    , array("type" => "noun", "content" => "peine", "fem" => true)
    , array("type" => "noun", "content" => "pensée", "fem" => true)
    , array("type" => "noun", "content" => "personne", "fem" => true)
    , array("type" => "noun", "content" => "peur", "fem" => true)
    , array("type" => "noun", "content" => "photo", "fem" => true)
    , array("type" => "noun", "content" => "pièce", "fem" => true)
    , array("type" => "noun", "content" => "pierre", "fem" => true)
    , array("type" => "noun", "content" => "place", "fem" => true)
    , array("type" => "noun", "content" => "police", "fem" => true)
    , array("type" => "noun", "content" => "porte", "fem" => true)
    , array("type" => "noun", "content" => "présence", "fem" => true)
    , array("type" => "noun", "content" => "prison", "fem" => true)
    , array("type" => "noun", "content" => "putain", "fem" => true)
    , array("type" => "noun", "content" => "question", "fem" => true)
    , array("type" => "noun", "content" => "raison", "fem" => true)
    , array("type" => "noun", "content" => "réponse", "fem" => true)
    , array("type" => "noun", "content" => "robe", "fem" => true)
    , array("type" => "noun", "content" => "route", "fem" => true)
    , array("type" => "noun", "content" => "salle", "fem" => true)
    , array("type" => "noun", "content" => "scène", "fem" => true)
    , array("type" => "noun", "content" => "seconde", "fem" => true)
    , array("type" => "noun", "content" => "sécurité", "fem" => true)
    , array("type" => "noun", "content" => "semaine", "fem" => true)
    , array("type" => "noun", "content" => "situation", "fem" => true)
    , array("type" => "noun", "content" => "soeur", "fem" => true)
    , array("type" => "noun", "content" => "soirée", "fem" => true)
    , array("type" => "noun", "content" => "suite", "fem" => true)
    , array("type" => "noun", "content" => "table", "fem" => true)
    , array("type" => "noun", "content" => "terre", "fem" => true)
    , array("type" => "noun", "content" => "tête", "fem" => true)
    , array("type" => "noun", "content" => "vérité", "fem" => true)
    , array("type" => "noun", "content" => "ville", "fem" => true)
    , array("type" => "noun", "content" => "voiture", "fem" => true)
    , array("type" => "noun", "content" => "habitude", "fem" => true, "forcedElision" => true)
    , array("type" => "noun", "content" => "heure", "fem" => true, "forcedElision" => true)
    , array("type" => "noun", "content" => "histoire", "fem" => true, "forcedElision" => true)

    // adjectives
    , array("type" => "adj", "content" => "bon", "fem" => "bonne")
    , array("type" => "adj", "content" => "bleu")
    , array("type" => "adj", "content" => "super", "fem" => "super", "femPlural" => "supers")
    , array("type" => "adj", "content" => "autre", "fem" => "autre", "femPlural" => "autres")
    , array("type" => "adj", "content" => "bizarre", "fem" => "bizarre", "femPlural" => "bizarres")
    , array("type" => "adj", "content" => "difficile", "fem" => "difficile", "femPlural" => "difficiles")
    , array("type" => "adj", "content" => "drôle", "fem" => "drôle", "femPlural" => "drôles")
    , array("type" => "adj", "content" => "étrange", "fem" => "étrange", "femPlural" => "étranges")
    , array("type" => "adj", "content" => "facile", "fem" => "facile", "femPlural" => "faciles")
    , array("type" => "adj", "content" => "grave", "fem" => "grave", "femPlural" => "graves")
    , array("type" => "adj", "content" => "impossible", "fem" => "impossible", "femPlural" => "impossibles")
    , array("type" => "adj", "content" => "jeune", "fem" => "jeune", "femPlural" => "jeunes")
    , array("type" => "adj", "content" => "juste", "fem" => "juste", "femPlural" => "justes")
    , array("type" => "adj", "content" => "libre", "fem" => "libre", "femPlural" => "libres")
    , array("type" => "adj", "content" => "malade", "fem" => "malade", "femPlural" => "malades")
    , array("type" => "adj", "content" => "pauvre", "fem" => "pauvre", "femPlural" => "pauvres")
    , array("type" => "adj", "content" => "possible", "fem" => "possible", "femPlural" => "possibles")
    , array("type" => "adj", "content" => "propre", "fem" => "propre", "femPlural" => "propres")
    , array("type" => "adj", "content" => "rouge", "fem" => "rouge", "femPlural" => "rouges")
    , array("type" => "adj", "content" => "sale", "fem" => "sale", "femPlural" => "sales")
    , array("type" => "adj", "content" => "simple", "fem" => "simple", "femPlural" => "simples")
    , array("type" => "adj", "content" => "tranquille", "fem" => "tranquille", "femPlural" => "tranquilles")
    , array("type" => "adj", "content" => "triste", "fem" => "triste", "femPlural" => "tristes")
    , array("type" => "adj", "content" => "vide", "fem" => "vide", "femPlural" => "vides")
    , array("type" => "adj", "content" => "doux", "plural" => "doux", "fem" => "douce", "femPlural" => "douces")
    , array("type" => "adj", "content" => "faux", "plural" => "faux", "fem" => "fausse", "femPlural" => "fausses")
    , array("type" => "adj", "content" => "français", "plural" => "français")
    , array("type" => "adj", "content" => "gros", "plural" => "gros", "fem" => "grosse", "femPlural" => "grosses")
    , array("type" => "adj", "content" => "heureux", "plural" => "heureux", "fem" => "heureuse", "femPlural" => "heureuses")
    , array("type" => "adj", "content" => "mauvais", "plural" => "mauvais")
    , array("type" => "adj", "content" => "sérieux", "plural" => "sérieux", "fem" => "sérieuse", "femPlural" => "sérieuses")
    , array("type" => "adj", "content" => "vieux", "plural" => "vieux", "fem" => "vieille", "femPlural" => "vieilles")
    , array("type" => "adj", "content" => "vrai")
    , array("type" => "adj", "content" => "ancien", "fem" => "ancienne", "femPlural" => "anciennes")
    , array("type" => "adj", "content" => "beau", "fem" => "belle", "femPlural" => "belles")
    , array("type" => "adj", "content" => "blanc", "fem" => "blanche", "femPlural" => "blanches")
    , array("type" => "adj", "content" => "certain")
    , array("type" => "adj", "content" => "chaud")
    , array("type" => "adj", "content" => "cher", "fem" => "chère", "femPlural" => "chères")
    , array("type" => "adj", "content" => "clair")
    , array("type" => "adj", "content" => "content")
    , array("type" => "adj", "content" => "dernier", "fem" => "dernière", "femPlural" => "dernières")
    , array("type" => "adj", "content" => "désolé")
    , array("type" => "adj", "content" => "différent")
    , array("type" => "adj", "content" => "droit")
    , array("type" => "adj", "content" => "entier", "fem" => "entière", "femPlural" => "entières")
    , array("type" => "adj", "content" => "fort")
    , array("type" => "adj", "content" => "froid")
    , array("type" => "adj", "content" => "gentil", "fem" => "gentille", "femPlural" => "gentilles")
    , array("type" => "adj", "content" => "grand")
    , array("type" => "adj", "content" => "haut")
    , array("type" => "adj", "content" => "humain")
    , array("type" => "adj", "content" => "important")
    , array("type" => "adj", "content" => "joli")
    , array("type" => "adj", "content" => "léger", "fem" => "légère", "femPlural" => "légères")
    , array("type" => "adj", "content" => "long", "fem" => "longue", "femPlural" => "longues")
    , array("type" => "adj", "content" => "meilleur")
    , array("type" => "adj", "content" => "mort")
    , array("type" => "adj", "content" => "noir")
    , array("type" => "adj", "content" => "nouveau", "plural" => "nouveaux", "fem" => "nouvelle", "femPlural" => "nouvelles")
    , array("type" => "adj", "content" => "pareil", "fem" => "pareille", "femPlural" => "pareilles")
    , array("type" => "adj", "content" => "petit")
    , array("type" => "adj", "content" => "plein")
    , array("type" => "adj", "content" => "premier", "fem" => "première", "femPlural" => "premières")
    , array("type" => "adj", "content" => "prêt")
    , array("type" => "adj", "content" => "prochain")
    , array("type" => "adj", "content" => "seul")
    , array("type" => "adj", "content" => "vert")
    , array("type" => "adj", "content" => "vivant")
    , array("type" => "adj", "content" => "gris", "plural" => "gris")
);